# Generated by Django 6.0.3 on 2026-03-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi (So'm)")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti")),
                ('is_successful', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli?')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_payments', to='gyms.gym', verbose_name='Sport zali')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_payments', to='members.member', verbose_name='Mijoz (Sportchi)')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershiptype', verbose_name="Ta'rif")),
            ],
            options={
                'verbose_name': "Zal to'lovi (Mijoz to'lagani)",
                'verbose_name_plural': "Zal to'lovlari (Mijoz to'lagani)",
            },
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi ($)")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti")),
                ('is_successful', models.BooleanField(default=False, verbose_name='Pul tushganmi?')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tranzaksiya ID')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='gyms.gym', verbose_name='Sport zali')),
            ],
            options={
                'verbose_name': "Platforma to'lovi (Superadmin tushumi)",
                'verbose_name_plural': "Platforma to'lovlari (Superadmin tushumi)",
            },
        ),
    ]
