# Generated by Django 6.0.3 on 2026-03-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Klub nomi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/', verbose_name='Klub logotipi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan sana')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL, verbose_name='Klub egasi / Administrator')),
            ],
            options={
                'verbose_name': 'Sport zali (Gym)',
                'verbose_name_plural': 'Sport zallari',
            },
        ),
        migrations.CreateModel(
            name='GymDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='Qurilma nomi (Masalan: Kirish, Chiqish)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='Seriya raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gyms.gym', verbose_name='Sport zali')),
            ],
            options={
                'verbose_name': 'Qurilma (Face ID)',
                'verbose_name_plural': 'Qurilmalar (Face ID)',
            },
        ),
    ]
