# Generated by Django 6.0.3 on 2026-03-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tarif nomi')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rifi")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Oylik'), ('YEARLY', 'Yillik'), ('LIFETIME', 'Cheksiz (Lifetime)')], default='MONTHLY', max_length=20, verbose_name='Tarif turi')),
                ('max_members', models.PositiveIntegerField(blank=True, null=True, verbose_name="Maksimal a'zolar soni")),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Analitika mavjud')),
                ('has_advanced_reports', models.BooleanField(default=False, verbose_name='Mukammal hisobotlar mavjud')),
                ('has_telegram_bot', models.BooleanField(default=True, verbose_name='Telegram bot mavjud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Superadmin Ta'rifi (Platforma uchun)",
                'verbose_name_plural': "Superadmin Ta'riflari",
            },
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Obuna faolmi?')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscription', to='gyms.gym', verbose_name='Sport zali')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscribers', to='subscriptions.subscriptionplan', verbose_name='Sotib olingan tarif')),
            ],
            options={
                'verbose_name': 'Sport zali obunasi',
                'verbose_name_plural': 'Sport zallari obunalari',
            },
        ),
    ]
