# Generated by Django 6.0.3 on 2026-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=50, verbose_name='Qabul qiluvchi turi (Mijoz / Zal)')),
                ('recipient_id', models.CharField(max_length=150, verbose_name='Telegram ID')),
                ('message_content', models.TextField(verbose_name='Yuborilgan xabar')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Yetib bordimi?')),
            ],
            options={
                'verbose_name': 'Telegram Xabarnomasi',
                'verbose_name_plural': 'Telegram Xabarnomalari',
            },
        ),
    ]
