# Generated by Django 6.0.3 on 2026-03-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ta'rif nomi (Zal ichida)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (So'm)")),
                ('duration_days', models.PositiveIntegerField(help_text='Masalan 30 kun', verbose_name='Muddati (Kunlarda)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='gyms.gym', verbose_name='Sport zali')),
            ],
            options={
                'verbose_name': "Zalning obuna ta'rifi",
                'verbose_name_plural': "Zalning obuna ta'riflari",
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Fotosurati')),
                ('face_id_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Face ID identifikatori (Qurilma yoki tizim bo'yicha)")),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID (Bot xabarlari uchun)')),
                ('membership_expires_at', models.DateField(blank=True, null=True, verbose_name='Tasdiqlangan muddat (qachongacha)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mijoz faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan sana')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gym', verbose_name='Sport zali')),
                ('active_membership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershiptype', verbose_name="Amaldagi ta'rif")),
            ],
            options={
                'verbose_name': 'Mijoz (Sportchi)',
                'verbose_name_plural': 'Mijozlar (Sportchilar)',
            },
        ),
    ]
