# Generated by Django 6.0.3 on 2026-03-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Tashrif vaqti')),
                ('is_success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli?')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name="Xabarnoma (masalan Qarz bo'lsa)")),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.gymdevice', verbose_name='Qurilma')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gym', verbose_name='Sport zali')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Tashrif (Davomat)',
                'verbose_name_plural': 'Tashriflar (Davomat)',
            },
        ),
    ]
